default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  port: 3306

development:
  <<: *default
  database: stringer_development

test:
  <<: *default
  database: stringer_test

production:
  <<: *default
  database: <%= ENV['STRINGER_DATABASE'] || "stringer" %>
  username: <%= ENV['STRINGER_DATABASE_USERNAME'] %>
  password: <%= ENV['STRINGER_DATABASE_PASSWORD'] %>
  host: <%= ENV['STRINGER_DATABASE_HOST'] %>
  port: <%= ENV['STRINGER_DATABASE_PORT'] %>